### ISSUE TITLE
Exception caught by image resource service

### ISSUE THREAD

**Issue by musayerlwa** [Michael-M-aher/location_picker_flutter_map#32]
I keep getting this error when I try to open the map screen:
════════ Exception caught by image resource service ════════════════════════════
Exception: Buffer parameter must not be null
════════════════════════════════════════════════════════════════════════════════

**Comment by CesarSP99** [comment]
I have the same issue, I'm getting a mix of that error:

```
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Buffer parameter must not be null

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:6950:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6764:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2307:60)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:182:15)
#4      _CNTPImageProvider._loadAsync (package:flutter_map_cancellable_tile_provider/flutter_map_cancellable_tile_provider.dart:146:22)
<asynchronous suspension>
URL: https://tile.openstreetmap.org/18/47407/101967.png
Fallback URL: null
Current provider: _CNTPImageProvider()
====================================================================================================
```

And this one:
```
E/flutter (17139): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (17139): #0      _FlutterLocationPickerState.onLocationChanged.<anonymous closure> (package:location_picker_flutter_map/src/location_picker.dart:413:25)
E/flutter (17139): <asynchronous suspension>
E/flutter (17139): 
```

**Comment by JoseAndresHV** [comment]
I have the same issue as well

**Comment by Michael-M-aher** [comment]
Fixed ✅
